### ISSUE TITLE
Question about docker pull a telomerehunter image

### ISSUE THREAD

**Issue by ryao-mdanderson** [cancerit/telomerehunter-docker#3]
Dear authors:

 I recently pulled a telmerhunter image from dockerhub, this is the command I used:
   singularity pull docker://erictdawson/telomerehunter
It appears to be version 1.0.4;

when one of HPC user tried this image with an appropriate command, it outputs
 /bin/bash: /usr/bin/lesspipe.sh: No such file or directory

I verified inside of the container image: 
 Singularity> ls -l /usr/bin/lesspipe.sh
 ls: cannot access '/usr/bin/lesspipe.sh': No such file or directory
 Singularity> ls -l /usr/bin/lesspipe   
 lrwxrwxrwx 1 root root 13 Mar 18  2019 /usr/bin/lesspipe -> /bin/lesspipe

May I know if this image is from your group? Is there a way I can retrieve a built image version 1.1.0 that appears in the 'Code'?

Thank you.

**Comment by ryao-mdanderson** [comment]
@mcast @keiranmraine @byb121 : May you please help me to take a look the above report issue? Thank you!

**Comment by keiranmraine** [comment]
@NickWilliamsSanger , @davidrajones are your best bet. I am no longer at the Sanger.

**Comment by mcast** [comment]
Hi @ryao-mdanderson,

(Yaobo also has left the Sanger.)

So far as I understand this project,
* it is fetching https://pypi.org/project/telomerehunter/ to build the docker image, so that is another place you could try installing the same software with different packaging
* and I believe our group has published this Docker recipe for the mutual benefit of others but currently has no remit to provide support for it. I could be wrong, or that might change. @davidrajones  ?

----

Attempting to help quickly:

The particular error you're seeing 
> [...] when one of HPC user tried this image with an appropriate command, it outputs
> `/bin/bash: /usr/bin/lesspipe.sh: No such file or directory`

does not look like a bioinformatic or dependency error - but it's hard to tell without knowing the "appropriate command".

I see no mention of `lesspipe` in this repo, nor https://github.com/linasieverling/TelomereHunter (I'm not sure if that is the upstream for PyPI or a parallel copy). My first guess is you have some code in a wrapper, possibly a `.bashrc` or similar user environment setup script, which is expecting `lesspipe.sh` to exist.

**Comment by mcast** [comment]
>  this is the command I used:
> `singularity pull docker://erictdawson/telomerehunter`
> It appears to be version 1.0.4;

I forgot to start at basics: I haven't checked exactly what that's pulling, but this is version 1.1.0 .  My zeroth guess is that you're not actually using this project's output!

**Comment by keiranmraine** [comment]
The images are on quay.io where all cancerit images live under the wtsicgp organisation:
https://quay.io/repository/wtsicgp/cgp-telomerehunter?tab=tags

Someone in CASM/cancerit needs to add this to the readme.

**Comment by mcast** [comment]
Thanks Keiran.

> Someone in CASM/cancerit needs to add this to the readme.

...and fix the "281 vulnerabilities across 90 packages"!  I'll draw gofor's attention to it.

**Comment by mcast** [comment]
Re: project alumni - please consider upvoting if you can,
* https://github.com/github/feedback/discussions/16308
* https://gitlab.com/gitlab-org/gitlab/-/issues/361904

**Comment by ryao-mdanderson** [comment]
@keiranmraine @mcast : Thank you very much for your replies.
I pulled a new container image followed by https://quay.io/repository/wtsicgp/cgp-telomerehunter?tab=tags.
It is under user's testing.

**Comment by mcast** [comment]
PR #4 is in progress with updated information, following this issue. I'm waiting for someone to define exactly what the support status is.

**Comment by ryao-mdanderson** [comment]
The 1.1.0 version container runs successfully. You might close this ticket.
Thank you all for your replies!

**Comment by mcast** [comment]
:+1:
